Import('RTT_ROOT')
from building import *

#生成RC_fs.c
Execute('fsgen fs RC_fs.c')

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
RC.c
RC.h
RC_fs.c
""")


path = [cwd, str(Dir('#'))]

group = DefineGroup('rc', src, depend = [''], CPPPATH = path)

Return('group')
