Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Glob('./*.c')
src += Glob('./*.h')
src += Glob('./*.cpp')
src += Glob('./*.hpp')

path = [cwd, str(Dir('#'))]

group = DefineGroup('app', src, depend = [''], CPPPATH = path)

Return('group')
